### ISSUE TITLE
Questions about the score calculation for tool use.

### ISSUE THREAD

**Issue by JakChen797** [JoeYing1019/UltraTool#3]
Thank you for the great paper. 
I have read the source code, and my understanding is that you use normalized Levenshtein Distance in tool_use.py to calculate the difference between parameters and return a score between [0,1]. My question is how this score is transformed into a score between [0,100] in the evaluation of Tool Usage in the paper?
Thank you very much for your answer.

**Comment by JoeYing1019** [comment]
Hi, thank you for your interest in our work. The normalized Levenshtein Distance score ranges from 0 to 1. You can multiply this value by 100 to obtain a percentage score, which will fall within the range of 0 to 100.
